name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
 push:
    branches:
      - main
 pull_request_target:
    branches:
      - main

jobs:
  pytest:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]
        python-version: [3.9]

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt --upgrade --quiet
        pip install --requirement tests/requirements.txt --quiet
        python --version
        pip --version
        pip list
      shell: bash
      
    - name: Flake8 Test
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --format github
        
    - name: Test with pytest-cov
      run: |
       coverage run --source FaceIDLight -m pytest FaceIDLight tests -v
       
    - name: Statistics
      if: success()
      run: |
        coverage report

  automerge:
    needs: pytest
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
        contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.automerge }}
