name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:
  # Trigger the workflow on push or pull request, but only for the master branch
 push:
    branches:
      - main
 pull_request:
    branches:
      - main

jobs:
  pytest:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 35

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt --upgrade --quiet
        pip install --requirement tests/requirements.txt --quiet
        pip install tflite-runtime --find-links https://google-coral.github.io/py-repo/tflite-runtime/ --quiet
        python --version
        pip --version
        pip list
      shell: bash
        
    - name: Test with pytest-cov
      run: |
       coverage run --source FaceIDLight -m py.test FaceIDLight tests -v
       
    - name: Statistics
      if: success()
      run: |
        coverage report
        
