# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --requirement requirements.txt --upgrade --quiet
        pip install --requirement tests/requirements.txt --quiet
        pip install https://github.com/google-coral/pycoral/releases/download/v1.0.1/tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl#sha256=ad9f5a127cfad78af207c0f17b303ebf76099775d423115d81e06518209ce459
        python --version
        pip --version
        pip list
    - name: Test with pytest
      run: |
        pytest
    - name: Test Coverage
      run: |
        pytest --cov
    - name: Statistics
      if: success()
      run: |
        coverage report
